<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboplan_mujoco</name>
  <version>0.6.1</version>
  <description>Mujoco simulation interface for RoboPlan.</description>
  <maintainer email="thisisdeahmed@gmail.com">Muhammad Ahmed</maintainer>
  <license>MIT</license>

  <url type="website">https://roboplan.readthedocs.io</url>
  <url type="repository">https://github.com/open-planning/roboplan</url>
  <url type="bugtracker">https://github.com/open-planning/roboplan/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>roboplan_core</depend>
  <depend>roboplan_hardware_interface</depend>
  <depend>glfw</depend>
  <depend>tinyxml2</depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-trimesh-pip</exec_depend>
  <exec_depend>python3-collada</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>