[build-system]
requires = ["cmeel[build] >=0.56"]
build-backend = "cmeel.build"

[project]
name = "roboplan-common"
version = "0.6.1"
description = "Shared runtime support for RoboPlan Python packages."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Sebastian Castro", email = "sebas.a.castro@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/open-planning/roboplan"

[tool.cmeel]
source = "."
run-tests = false

[tool.pixi.package]
publish = true

[tool.pixi.package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[tool.pixi.package.build.config]
compilers = ["cxx"]


[tool.pixi.package.host-dependencies]
cmake = ">=3.22"
ninja = "*"
python = ">=3.10,<3.15"
