[build-system]
requires = ["cmeel[build] >=0.56", "nanobind >=1.3.2", "roboplan-common"]
build-backend = "cmeel.build"

[project]
name = "roboplan-example-models"
version = "0.6.1"
description = "Robot descriptions for RoboPlan testing and examples."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Sebastian Castro", email = "sebas.a.castro@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dependencies = ["roboplan-common"]

[project.urls]
Homepage = "https://github.com/open-planning/roboplan"

[tool.cmeel]
source = "."
run-tests = false
configure-args = [
    "-DBUILD_PYTHON_BINDINGS=ON",
    "-DBUILD_TESTING=OFF",
    "-DGENERATE_PYTHON_STUBS=OFF",
]

[tool.pixi.package]
publish = true

[tool.pixi.package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[tool.pixi.package.build.config]
compilers = ["cxx"]

extra-args = [
    "-DBUILD_PYTHON_BINDINGS=ON",
    "-DBUILD_TESTING=OFF",
    "-DGENERATE_PYTHON_STUBS=OFF",
]

[tool.pixi.package.host-dependencies]
cmake = ">=3.22"
nanobind = ">=2.8"
ninja = "*"
python = ">=3.10,<3.15"
roboplan-common = { path = "../roboplan_common" }

[tool.pixi.package.run-dependencies]
roboplan-common = { path = "../roboplan_common" }

[tool.pixi.package.target.win-64.host-dependencies]
dlfcn-win32 = "*"

[tool.pixi.package.target.win-64.run-dependencies]
dlfcn-win32 = "*"
