#!/bin/bash

# Helper script that checks diffs with the stub (.pyi) files generated by nanobind.

if ! git diff --exit-code --shortstat -- 'bindings/src/roboplan/roboplan_ext/*.pyi'; then
    echo "::error::The .pyi stub files are out of sync with the source code. Make sure to rebuild the Python bindings without symlink builds and commit the changes."
    echo "Git Diff:"
    git diff -- 'bindings/src/roboplan/roboplan_ext/*.pyi'
    exit 1
fi
echo "✅ .pyi stub files look good!"
